site_name: eQual framework documentation
site_url: https://doc.equal.run/
docs_dir: docs
# dev_addr: 127.0.0.1:8000
repo_name: equal
repo_url: https://github.com/equalframework/equal
edit_uri: ""
theme:
  name: material
  favicon: 'assets/img/favicon.png'
  logo: 'assets/img/eq_logo.png'
  feature:
    tabs: true
  features: 
    - navigation.instant  
    - navigation.tracking
    - navigation.tabs
  # 404 page
  static_templates:
    - 404.html
extra_css:
  - 'assets/css/extra.css'
plugins:
  - search  
  - mike:
      canonical_version: null
      version_selector: true
      css_dir: css
extra:
  version:
    provider: mike
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - 'Welcome': 
      - 'eQual': 'index.md'
      - 'Release notes': 'welcome/release-notes.md'
      - 'Contribution Guide': 'welcome/contribution-guide.md'
  - 'Getting Started':
      - 'Installation': 'getting-started/installation.md'
      - 'Quick Start': 'getting-started/quick-start.md'
      - 'Configuration': 'getting-started/configuration.md'
      - 'Deployment': 'getting-started/deployment.md'
  - 'Architecture Concepts':
      - 'HTTP native': 'architecture-concepts/http-native.md'
      - 'Services': 'architecture-concepts/services.md'
      - 'ORM': 'architecture-concepts/orm.md'
      - 'Collections': 'architecture-concepts/collections.md'
      - 'Dependency injection': 'architecture-concepts/dependency-injection.md'
      - 'Domains': 'architecture-concepts/domains.md'
      - 'Operations': 'architecture-concepts/operations.md'
      - 'Usages': 'architecture-concepts/usages.md'
  - 'Usage':
     - 'Built-in tools': 'usage/built-in-tools.md'
     - 'Directory Structure': 'usage/directory-structure.md'
     - 'Packages': 'usage/packages.md'
     - 'Model Definition': 'usage/model-definition.md'
     - 'Actions': 'usage/actions.md'
     - 'Controllers': 'usage/controllers.md'
     - 'CRUD': 'usage/crud.md'
     - 'Searching': 'usage/searching.md'
     - 'Validation': 'usage/validation.md'
     - 'Routing': 'usage/routing.md'
     - 'Views': 'usage/views.md'
     - 'i18n': 'usage/i18n.md'
     - 'Error Handling': 'usage/error-handling.md'
     - 'Debugging': 'usage/debugging.md'
     - 'Testing': 'usage/testing.md'
  - 'How-Tos & Examples':
     - 'Generic Cheat Sheet': 'howtos-and-examples/generic-cheat-sheet.md'
     - 'Basic Controller' : 'howtos-and-examples/basic-controller.md'
     - 'ReST API': 'howtos-and-examples/rest-api.md'
     - 'Basic WebApp' : 'howtos-and-examples/basic-webapp.md'
  - 'Advanced':
     - 'Security': 'advanced/security.md'
     - 'Workflows': 'advanced/workflows.md'
     - 'Logging': 'advanced/logging.md'
     - 'Remote APIs': 'advanced/remote-apis.md'
     - 'Cascade Configuration': 'advanced/cascade-configuration.md'
     - 'CI/CD' : 'advanced/ci-cd.md'
     - 'External libraries' : 'advanced/external-libraries.md'
  - 'Low-Code & tools':
     - 'Low-Code' : 'low-code/low-code.md'
     - 'eQual Workbench' : 'low-code/workbench.md'
  - 'Contact & Support':
     - 'Contact': 'contact-and-support/contact.md'
     - 'Support': 'contact-and-support/support.md'
